### ISSUE TITLE
Duplicate Symbol Issue

### ISSUE THREAD

**Issue by chirag225** [slavavdovichenko/MediaLibDemos3x#44]
duplicate symbol _ff_log2_tab in:
    /Users/bla/Desktop/blaa 14:9:15/support/lib/libav-11.4/lib/libavutil.a(log2_tab.o)
    /Users/bla/Desktop/blaa 14:9:15/support/lib/libav-11.4/lib/libavformat.a(log2_tab.o)
duplicate symbol _ff_log2_tab in:
    /Users/bla/Desktop/blaa 14:9:15/support/lib/libav-11.4/lib/libavutil.a(log2_tab.o)
    /Users/bla/Desktop/blaa 14:9:15/support/lib/libav-11.4/lib/libavcodec.a(log2_tab.o)
ld: 2 duplicate symbols for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by chirag225** [comment]
Hi @slavavdovichenko please check this error, i can not understand what file duplicat

**Comment by slavavdovichenko** [comment]
I cannot reproduce this situation on my samples

**Comment by chirag225** [comment]
Hi thank you for your replay Can you Explain how can i handle this duplicate symbol error

**Comment by slavavdovichenko** [comment]
Check your project target if the kit of the libs is like here:
- in Build Phases -> Link Binary With Libraries
<img width="1013" alt="screen shot 2015-09-23 at 10 47 22 am" src="https://cloud.githubusercontent.com/assets/429207/10040299/fe08c328-61e2-11e5-9dd3-56130f90c8b9.png">
- in Build Settings -> Search Paths -> Library SearchPaths
<img width="1275" alt="screen shot 2015-09-23 at 10 48 14 am" src="https://cloud.githubusercontent.com/assets/429207/10040333/44b66fbe-61e3-11e5-92fc-447e33266e50.png">

**Comment by chirag225** [comment]
Thank you sir this is working now

**Comment by satyamub** [comment]
@chirag225 @slavavdovichenko  I am experiencing the same issue.. The code line which if I add I get the duplicate symbol issue.
I have checked the above comments and checked that all are included.

 MPMediaDecoder   *decoder = [[MPMediaDecoder alloc] initWithView:previewView];
Another thing I get  to know that its suggested to add CoreData.framework in the page however in this screenshot in above comment, its not getting shown. Why so?

Please help me out!!!

**Comment by satyamub** [comment]
I am using Xcode 6.4 thats why I have used .dylib file instead of tbd file. I am getting the below errors.

duplicate symbol _llvm.cmdline in:
    /Users/Exelanz/Desktop/iOS Development/RTMPObjCPlayer/RTMPObjCPlayer/lib/MediaLibiOS3x/MediaLibiOS.a(MPMediaDecoder.o)
    /Users/Exelanz/Desktop/iOS Development/RTMPObjCPlayer/RTMPObjCPlayer/lib/libav-11.4/lib/libavcodec.a(vorbis_parser.o)
duplicate symbol _llvm.embedded.module in:
    /Users/Exelanz/Desktop/iOS Development/RTMPObjCPlayer/RTMPObjCPlayer/lib/MediaLibiOS3x/MediaLibiOS.a(MPMediaDecoder.o)
    /Users/Exelanz/Desktop/iOS Development/RTMPObjCPlayer/RTMPObjCPlayer/lib/libav-11.4/lib/libavcodec.a(vorbis_parser.o)
duplicate symbol _llvm.cmdline in:
    /Users/Exelanz/Desktop/iOS Development/RTMPObjCPlayer/RTMPObjCPlayer/lib/MediaLibiOS3x/MediaLibiOS.a(MPMediaDecoder.o)
    /Users/Exelanz/Desktop/iOS Development/RTMPObjCPlayer/RTMPObjCPlayer/lib/libav-11.4/lib/libavcodec.a(xiph.o)
duplicate symbol _llvm.embedded.module in:
    /Users/Exelanz/Desktop/iOS Development/RTMPObjCPlayer/RTMPObjCPlayer/lib/MediaLibiOS3x/MediaLibiOS.a(MPMediaDecoder.o)
    /Users/Exelanz/Desktop/iOS Development/RTMPObjCPlayer/RTMPObjCPlayer/lib/libav-11.4/lib/libavcodec.a(xiph.o)
ld: 696 duplicate symbols for architecture x86_64

**Comment by satyamub** [comment]
I got the issue its because of the tbd file I am not using because I am working on the Xcode 6.4. @slavavdovichenko how can I use Xcode 6.4 to use this library????

**Comment by slavavdovichenko** [comment]
Hi,

You can get the older version from http://www.themidnightcoders.com/download.html (3.3.1).
But maybe it is better to upgrade the Xcode?
